### ISSUE TITLE
The built archive doesn't exist for the publish command

### ISSUE THREAD

**Issue by artis3n** [artis3n/ansible_galaxy_collection#14]
The first command executes successfully, presumably, but the publish command fails because it cannot find the .tar.gz file.

Also, I am not handling errors on the promise and it does not propagate up to the action. So the error is thrown in the log, but the step thinks it completed successfully.

```bash
Run artis3n/ansible_galaxy_collection@v1.0.6
Building collection artis3n.github_version, version 1.0.1
ansible-galaxy collection build
Created collection for artis3n.github_version at /home/runner/work/github_version-ansible_plugin/github_version-ansible_plugin/artis3n-github_version-1.0.1.tar.gz
ansible-galaxy collection publish artis3n.github_version-1.0.1.tar.gz --api-key=***
Publishing collection artifact '/home/runner/work/github_version-ansible_plugin/github_version-ansible_plugin/artis3n.github_version-1.0.1.tar.gz' to default https://galaxy.ansible.com/api/
ERROR! The collection path specified '/home/runner/work/github_version-ansible_plugin/github_version-ansible_plugin/artis3n.github_version-1.0.1.tar.gz' does not exist.
(node:3189) UnhandledPromiseRejectionWarning: Error: The process 'ansible-galaxy' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/artis3n/ansible_galaxy_collection/v1.0.6/dist/index.js:597:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/artis3n/ansible_galaxy_collection/v1.0.6/dist/index.js:580:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/artis3n/ansible_galaxy_collection/v1.0.6/dist/index.js:480:27)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:3189) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3189) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

https://github.com/artis3n/github_version-ansible_plugin/commit/078b9c0e1fac7e20e733fc34dbdec1ac66453d8a/checks?check_suite_id=276872865

**Comment by artis3n** [comment]
Fixed by #15
